# Generated by Django 6.0.7 on 2026-07-24 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=255)),
                ('deal_owner', models.JSONField(blank=True, default=list)),
                ('deal_stage', models.CharField(choices=[('Contact', 'Contact'), ('Qualified', 'Qualified'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Contact', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Note', 'Note'), ('Call', 'Call'), ('Task', 'Task'), ('Meeting', 'Meeting'), ('Email', 'Email')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('connected', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('call_time', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to='deals.dealactivity')),
            ],
        ),
        migrations.CreateModel(
            name='DealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deal_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.EmailField(max_length=254)),
                ('sentAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organized_by', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to='deals.dealactivity')),
            ],
        ),
    ]
