# Generated by Django 6.0.7 on 2026-07-24 19:50

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('jobTitle', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('contactOwner', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leadStatus', models.CharField(choices=[('New', 'New'), ('Open', 'Open '), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Qualified', 'Qualified'), ('Lost', 'Lost'), ('Converted', 'Converted')], default='New', max_length=20)),
                ('aiSummary', models.TextField(blank=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.EmailField(max_length=254)),
                ('sentAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list)),
                ('bcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.CharField(blank=True, default='', max_length=255)),
                ('outcome', models.CharField(blank=True, default='', max_length=255)),
                ('callTime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.email')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('organized_by', models.CharField(blank=True, default='', max_length=255)),
                ('attendees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('priority', models.CharField(blank=True, default='', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
            ],
        ),
    ]
