# Generated by Django 6.0.7 on 2026-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=255)),
                ('ticket_status', models.CharField(choices=[('New', 'New'), ('Waiting on contact', 'Waiting on contact'), ('Waiting on us', 'Waiting on us'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50, null=True)),
                ('source', models.CharField(blank=True, choices=[('Chat', 'Chat'), ('Email', 'Email'), ('Phone', 'Phone')], max_length=50, null=True)),
                ('ticket_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
